# Generated by Django 4.1.2 on 2022-10-20 01:01

from django.db import migrations
import django_cpf_cnpj.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='cpf',
            field=django_cpf_cnpj.fields.CPFField(max_length=14),
        ),
    ]
