# Generated by Django 4.1.2 on 2022-10-22 18:35

from django.db import migrations, models
import django_cpf_cnpj.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_usuario_cpf'),
    ]

    operations = [
        migrations.CreateModel(
            name='Loja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('razao_social', models.CharField(max_length=150)),
                ('cnpj', django_cpf_cnpj.fields.CNPJField(max_length=18)),
                ('endereco', models.CharField(max_length=100)),
                ('latitude', models.DecimalField(blank=True, decimal_places=16, max_digits=22)),
                ('longitude', models.DecimalField(blank=True, decimal_places=16, max_digits=22)),
            ],
        ),
    ]
