# Generated by Django 4.1.2 on 2022-10-22 22:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_loja'),
    ]

    operations = [
        migrations.AddField(
            model_name='loja',
            name='data_criacao',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='loja',
            name='data_modificacao',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
