# Generated by Django 4.1.2 on 2022-10-23 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_loja_data_criacao_loja_data_modificacao'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='loja',
            options={'ordering': ['-nome']},
        ),
        migrations.AlterField(
            model_name='loja',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=16, max_digits=22, null=True),
        ),
        migrations.AlterField(
            model_name='loja',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=16, max_digits=22, null=True),
        ),
    ]
