# Generated by Django 4.1.2 on 2022-10-24 14:32

from django.db import migrations, models
import django_cpf_cnpj.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_loja_options_alter_loja_latitude_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entregador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
                ('cpf', django_cpf_cnpj.fields.CPFField(max_length=14)),
                ('email', models.EmailField(max_length=254)),
                ('telefone', models.CharField(max_length=25)),
                ('chave_pix', models.CharField(max_length=80)),
                ('endereco', models.CharField(max_length=100)),
                ('data_nascimento', models.DateField()),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_modificacao', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-nome'],
            },
        ),
    ]
