# Generated by Django 4.1.2 on 2022-10-28 21:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_categoria_cliente_alter_entregador_options_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DetalhesVenda',
            new_name='DetalheVenda',
        ),
        migrations.AddField(
            model_name='entregador',
            name='loja',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.loja'),
            preserve_default=False,
        ),
    ]
