# Generated by Django 4.1.2 on 2022-11-02 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_venda_data_venda'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venda',
            name='forma_da_venda',
            field=models.CharField(choices=[('Presencial', 'Presencial'), ('Whatsapp', 'Whatsapp'), ('Ifood', 'Ifood'), ('Ubereats', 'UberEats'), ('Telefone', 'Telefone'), ('Instagram', 'Instagram'), ('Facebook', 'Facebook')], max_length=60),
        ),
        migrations.AlterField(
            model_name='venda',
            name='forma_pagamento',
            field=models.CharField(choices=[('Dinheiro', 'Dinheiro'), ('Pix', 'PIX'), ('Cartão de Crédito - Visa', 'Cartão de Crédito - Visa'), ('Cartão de Crédito - Master', 'Cartão de Crédito - Master'), ('Cartão de Crédito - Elo', 'Cartão de Crédito - Elo'), ('Cartão de Crédito - Outros', 'Cartão de Crédito - Outros'), ('Débito', 'Débito')], max_length=60),
        ),
    ]
