# Generated by Django 4.1.2 on 2022-11-12 12:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_venda_data_venda'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalhevenda',
            name='preco',
            field=models.DecimalField(decimal_places=2, default=(), max_digits=8),
        ),
        migrations.AlterField(
            model_name='detalhevenda',
            name='produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produtos', to='core.produto'),
        ),
    ]
