# Generated by Django 4.1.2 on 2022-11-12 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_detalhevenda_preco_alter_detalhevenda_produto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalhevenda',
            name='preco',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
