# Generated by Django 4.1.2 on 2022-11-14 23:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_detalhevenda_preco'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detalhevenda',
            name='preco',
        ),
    ]
