# Generated by Django 4.1.2 on 2022-11-15 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_remove_detalhevenda_preco'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalhevenda',
            name='venda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendas', to='core.venda'),
        ),
    ]
